validation:
  number:
    zero: 0
    six: 6
  name_max: 100
  email_max: 255
  password_min: 6
  phone_min: 10
  id_card_min: 9
  address_max: 255
  min_point: 0
  max_point: 6
product:
  min_quantity: 1
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
